config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'lists#index'

  resources :movies, only: [:index]
  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:create]
  end

  get '/my_lists', to: 'lists#my_lists', as: :my_lists
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, uniqueness: true
  validates :title, :overview, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true, uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  include Pundit
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    authorize(@bookmark)

    if @bookmark.save
      redirect_to list_path(@list), notice: "Movie added to list!"
    else
      render 'lists/show'
    end
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  skip_after_action :verify_authorized, only: :my_lists
  after_action :verify_policy_scoped, only: :my_lists

  def index
    @lists = policy_scope(List)
  end

  def show
    @list = List.find(params[:id])
    authorize(@list)
    @bookmark = Bookmark.new
    @bookmark.list = @list
  end

  def new
    @list = List.new
    authorize(@list)
  end

  def create
    @list = List.new(list_params)
    @list.user = current_user
    authorize(@list)

    if @list.save
      redirect_to list_path(@list), notice: "List created!"
    else
      render :new
    end
  end

  def my_lists
    @lists = policy_scope(List).where(user: current_user)
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = policy_scope(Movie)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
  def list_photo(list)
    list.photo.attached? ? cl_image_path(list.photo.key) : "https://images.unsplash.com/photo-1505775561242-727b7fba20f0?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80"
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>Movie Watch List</title>
    
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>

    <% if content_for?(:banner) %>
      <%= yield :banner %>
    <% else %>
      <%= render 'shared/banner', heading: "Movie Watch List", image: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80" %>
    <% end %>

    <div class="container py-3">

      <%= render 'shared/flashes' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/lists/index.html.erb
<div class="row">
  <% @lists.each do |list| %>
    <div class="col-12 col-md-4 my-2">
      <%= link_to list_path(list), class: 'list-link' do %>
        <div class="list-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= list_photo(list) %>)">
          <%= list.name %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/lists/my_lists.html.erb
<div class="d-flex justify-content-between align-items-center mb-3">
  <h2>My Lists</h2>
  <%= link_to "Add New List", new_list_path, class: 'btn btn-primary' %>
</div>

<div class="row">
  <% @lists.each do |list| %>
    <div class="col-12 col-md-4 my-2">
      <%= link_to list_path(list), class: 'list-link' do %>
        <div class="list-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= list_photo(list) %>)">
          <%= list.name %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

<% if @lists.empty? %>
  <p>You have not added any lists yet.</p>
<% end %>

app/views/lists/new.html.erb
<h2>Add a new list</h2>

<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file, class: 'custom-file-input' %>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/lists/show.html.erb
<% content_for :banner do %>
  <%= render 'shared/banner', heading: @list.name, image: list_photo(@list) %>
<% end %>

<div class="d-flex justify-content-between align-items-center">
  <h2><%= pluralize(@list.bookmarks.count, 'movie') %> bookmarked by <%= @list.user.username %></h2>
  <div>
    <% if policy(@bookmark).create? %>
      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#bookmarkModal">
        Add a movie
      </button>
    <% end %>
  </div>
</div>

<div class="row">
  <% @list.bookmarks.each do |bookmark| %>
    <div class="col-12 col-md-6 col-lg-4 d-flex">
      <div class="card my-3 bookmark-card flex-fill">
          <img src="https://image.tmdb.org/t/p/w300<%= bookmark.movie.poster_url %>" class="card-img-top" alt="<%= bookmark.movie.title %> poster">
          <div class="card-body">
            <div class="d-flex justify-content-between mb-2">
            <h5 class="card-title pr-2"><%= bookmark.movie.title %></h5>
            <p class="card-text text-center"><i class="fas fa-star text-warning"></i><br><%= bookmark.movie.rating %></p>
            </div>
            <p class="card-text text-muted"><%= bookmark.movie.overview %></p>
            <p class="card-text font-italic"><i class="fas fa-quote-left mr-2"></i> <%= bookmark.comment %></p>
          </div>
        </div>
    </div>
  <% end %>
</div>

<% if policy(@bookmark).create? %>
  <div class="modal fade" id="bookmarkModal" tabindex="-1" aria-labelledby="bookmarkModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="bookmarkModalLabel">Add a movie to this list</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <%= simple_form_for [@list, @bookmark] do |f| %>
          <div class="modal-body">
            <%= f.association :movie, collection: Movie.all.order(:title), input_html: { class: 'select2', style: 'width: 100%' } %>
            <%= f.input :comment %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <%= f.submit 'Add movie', class: 'btn btn-primary' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/movies/index.html.erb
<div class="row">
  <% @movies.each do |movie| %>
    <div class="col-12 col-sm-6 col-md-3">
      <div class="card bg-dark text-white my-3">
        <img src="https://image.tmdb.org/t/p/w500/<%= movie.poster_url %>" class="card-img" alt="<%= movie.title %>">
        <div class="card-header">
          <%= movie.title %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/pages/home.html.erb
<h1>Movie Watch List</h1>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image %>);">
  <h1 class="text-center"><%= heading %></h1>
</div>

app/views/shared/_flashes.html.erb
<% flash.each do |type, msg| %>
  <div class="alert alert-info alert-flash" role="alert">
    <%= msg %>
    <button type="button" class="close pl-3" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
  <%= link_to "Movie Watch List", root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "My lists", my_lists_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "All movies", movies_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>